// <auto-generated />
namespace entity_framework_codefirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddHeoAndChuongHeo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHeoAndChuongHeo));
        
        string IMigrationMetadata.Id
        {
            get { return "202310110858315_AddHeoAndChuongHeo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
